name: SunnyCredits
version: '0.1-ALPHA'
main: live.deact.sunnycredits.SunnyCredits
api-version: '1.20'
depend:
  - PlaceholderAPI
commands:
  credits:
    description: Shows the balance
    usage: /credits [shop]
  creditsadmin:
    description: Admin commands for currency
permissions:
  credits.admin:
    description: Allows access to admin commands
    default: op